// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {store} from '../models';
import {context} from '../models';

export function ApplyHistory(arg1:string,arg2:boolean):Promise<void>;

export function ApplyRandomHistory(arg1:boolean):Promise<void>;

export function ApplyWallpaper(arg1:boolean):Promise<void>;

export function BrowserOpenURL(arg1:string):Promise<void>;

export function CleanupByRetainDays(arg1:number):Promise<number>;

export function CleanupLogs():Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function FetchToday(arg1:number,arg2:number,arg3:number):Promise<app.CurrentResult>;

export function GetBaseDir():Promise<string>;

export function GetConfig():Promise<store.Config>;

export function GetContext():Promise<context.Context>;

export function GetImageDataURL(arg1:string):Promise<string>;

export function GetVersionInfo():Promise<app.VersionInfo>;

export function GetWallpaperSupport():Promise<boolean|string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function ListHistory():Promise<Array<store.HistoryItem>>;

export function OpenBaseDir():Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenLogsDir():Promise<void>;

export function Quit():Promise<void>;

export function ResetApplication():Promise<void>;

export function ResetSettings():Promise<void>;

export function SaveConfig(arg1:store.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetBaseDir(arg1:string):Promise<void>;

export function SetupTray(arg1:Array<number>,arg2:Array<number>):Promise<any|any>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitWatermark(arg1:string):Promise<void>;
