// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyHistory'](arg1, arg2, arg3);
}

export function ApplyHistoryToMonitor(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ApplyHistoryToMonitor'](arg1, arg2, arg3, arg4);
}

export function ApplyRandomHistory(arg1, arg2) {
  return window['go']['app']['App']['ApplyRandomHistory'](arg1, arg2);
}

export function ApplyWallpaper(arg1, arg2) {
  return window['go']['app']['App']['ApplyWallpaper'](arg1, arg2);
}

export function AssetsHandler() {
  return window['go']['app']['App']['AssetsHandler']();
}

export function BrowserOpenURL(arg1) {
  return window['go']['app']['App']['BrowserOpenURL'](arg1);
}

export function CleanupByRetainDays(arg1) {
  return window['go']['app']['App']['CleanupByRetainDays'](arg1);
}

export function CleanupLogs() {
  return window['go']['app']['App']['CleanupLogs']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['app']['App']['DeleteHistory'](arg1);
}

export function FetchToday(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchToday'](arg1, arg2, arg3);
}

export function GetBaseDir() {
  return window['go']['app']['App']['GetBaseDir']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetCurrentItem() {
  return window['go']['app']['App']['GetCurrentItem']();
}

export function GetImageDataURL(arg1) {
  return window['go']['app']['App']['GetImageDataURL'](arg1);
}

export function GetImageURL(arg1) {
  return window['go']['app']['App']['GetImageURL'](arg1);
}

export function GetMonitorWallpapers() {
  return window['go']['app']['App']['GetMonitorWallpapers']();
}

export function GetMonitors() {
  return window['go']['app']['App']['GetMonitors']();
}

export function GetThumbnailURL(arg1) {
  return window['go']['app']['App']['GetThumbnailURL'](arg1);
}

export function GetVersionInfo() {
  return window['go']['app']['App']['GetVersionInfo']();
}

export function GetWallpaperSupport() {
  return window['go']['app']['App']['GetWallpaperSupport']();
}

export function IsAutoStartEnabled() {
  return window['go']['app']['App']['IsAutoStartEnabled']();
}

export function ListHistory() {
  return window['go']['app']['App']['ListHistory']();
}

export function OpenBaseDir() {
  return window['go']['app']['App']['OpenBaseDir']();
}

export function OpenDataDir() {
  return window['go']['app']['App']['OpenDataDir']();
}

export function OpenLogsDir() {
  return window['go']['app']['App']['OpenLogsDir']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ResetApplication() {
  return window['go']['app']['App']['ResetApplication']();
}

export function ResetSettings() {
  return window['go']['app']['App']['ResetSettings']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SetBaseDir(arg1) {
  return window['go']['app']['App']['SetBaseDir'](arg1);
}

export function SetupTray(arg1, arg2) {
  return window['go']['app']['App']['SetupTray'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function SubmitWatermark(arg1) {
  return window['go']['app']['App']['SubmitWatermark'](arg1);
}
