// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyHistory(arg1, arg2) {
  return window['go']['app']['App']['ApplyHistory'](arg1, arg2);
}

export function ApplyWallpaper(arg1) {
  return window['go']['app']['App']['ApplyWallpaper'](arg1);
}

export function CleanupByRetainDays(arg1) {
  return window['go']['app']['App']['CleanupByRetainDays'](arg1);
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['app']['App']['DeleteHistory'](arg1);
}

export function FetchToday(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchToday'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetImageDataURL(arg1) {
  return window['go']['app']['App']['GetImageDataURL'](arg1);
}

export function GetWallpaperSupport() {
  return window['go']['app']['App']['GetWallpaperSupport']();
}

export function ListHistory() {
  return window['go']['app']['App']['ListHistory']();
}

export function OpenDataDir() {
  return window['go']['app']['App']['OpenDataDir']();
}

export function OpenLogsDir() {
  return window['go']['app']['App']['OpenLogsDir']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SubmitWatermark(arg1) {
  return window['go']['app']['App']['SubmitWatermark'](arg1);
}
