// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {store} from '../models';

export function ApplyHistory(arg1:string,arg2:boolean):Promise<void>;

export function ApplyWallpaper(arg1:boolean):Promise<void>;

export function CleanupByRetainDays():Promise<number>;

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function FetchToday(arg1:number,arg2:number,arg3:number):Promise<app.CurrentResult>;

export function GetConfig():Promise<store.Config>;

export function GetImageDataURL(arg1:string):Promise<string>;

export function GetWallpaperSupport():Promise<boolean|string>;

export function ListHistory():Promise<Array<store.HistoryItem>>;

export function OpenDataDir():Promise<void>;

export function OpenLogsDir():Promise<void>;

export function SaveConfig(arg1:store.Config):Promise<void>;
