// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyHistory(arg1) {
  return window['go']['app']['App']['ApplyHistory'](arg1);
}

export function ApplyRandomHistory() {
  return window['go']['app']['App']['ApplyRandomHistory']();
}

export function ApplyWallpaper() {
  return window['go']['app']['App']['ApplyWallpaper']();
}

export function BrowserOpenURL(arg1) {
  return window['go']['app']['App']['BrowserOpenURL'](arg1);
}

export function CleanupByRetainDays(arg1) {
  return window['go']['app']['App']['CleanupByRetainDays'](arg1);
}

export function CleanupLogs() {
  return window['go']['app']['App']['CleanupLogs']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['app']['App']['DeleteHistory'](arg1);
}

export function FetchToday(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchToday'](arg1, arg2, arg3);
}

export function GetBaseDir() {
  return window['go']['app']['App']['GetBaseDir']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetImageDataURL(arg1) {
  return window['go']['app']['App']['GetImageDataURL'](arg1);
}

export function GetVersionInfo() {
  return window['go']['app']['App']['GetVersionInfo']();
}

export function GetWallpaperSupport() {
  return window['go']['app']['App']['GetWallpaperSupport']();
}

export function IsAutoStartEnabled() {
  return window['go']['app']['App']['IsAutoStartEnabled']();
}

export function ListHistory() {
  return window['go']['app']['App']['ListHistory']();
}

export function OpenBaseDir() {
  return window['go']['app']['App']['OpenBaseDir']();
}

export function OpenDataDir() {
  return window['go']['app']['App']['OpenDataDir']();
}

export function OpenLogsDir() {
  return window['go']['app']['App']['OpenLogsDir']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ResetApplication() {
  return window['go']['app']['App']['ResetApplication']();
}

export function ResetSettings() {
  return window['go']['app']['App']['ResetSettings']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SetBaseDir(arg1) {
  return window['go']['app']['App']['SetBaseDir'](arg1);
}

export function SetupTray(arg1, arg2) {
  return window['go']['app']['App']['SetupTray'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function SubmitWatermark(arg1) {
  return window['go']['app']['App']['SubmitWatermark'](arg1);
}
